### ISSUE TITLE
Server side rendering does not work with the latest version (2.0.3)

### ISSUE THREAD

**Issue by chengjia0807** [cssinjs/css-vendor#109]
Hi, 

I got this error with the latest version:

"document is not defined"

You can do a global search for "document.documentElement" then you'll get it.

Old version 2.0.2 got no issue.

Hope it can be fixed in short

Thanks
CJ

**Comment by AleshaOleg** [comment]
Hi @chengjia0807,

thanks for reporting.

https://github.com/cssinjs/css-vendor/pull/108

**Comment by AleshaOleg** [comment]
`2.0.4` released
