### ISSUE TITLE
Throws "Unspecified Error" inside of `supportedValue` when `content` property is used.

### ISSUE THREAD

**Issue by swernerx** [cssinjs/css-vendor#128]
We are using `css-vendor` as part of our material-ui based application. Somewhere in this application or a component we are using a CSS property `content` might be set. IE11 throws inside `supportedValue()` when trying to check the possibility to apply it. It might (correctly) be related to the fact that generated content can not be applied to the internally used `p` element. Probably there should be some ignore list ... or this property should be added to it, if such a list is already available.

IE11 just reports an "Unspecified error". 

The issue is related to [this code](https://github.com/cssinjs/css-vendor/blob/c838fb5ffd73886abba9d4499dba029284491d28/src/supported-value.js#L82)

```js
el.style[property] = prefixedValue
```

If modified with a try-catch to ignore the error it at least works. But this might also lead to the fact that the property is not applied in the end.

```js
try {
  el.style[property] = prefixedValue;
} catch(ex) {
  console.warn("Unable to validate supported value for CSS property: " + property + "! Error: " + ex);
}
```

We know that IE11 is old and actually nobody likes it. :)

For others: Our "solution" for right now is to have a local copy of `css-vendor` inside a `node_overrides` folder. Then we added this to our `package.json`:

```
"resolutions": {
  "**/css-vendor": "file:./node_overrides/css-vendor-2.0.5-ie11-fixed"
},
```

which is used by Yarn for overriding the install source.

**Comment by AleshaOleg** [comment]
https://github.com/cssinjs/css-vendor/pull/134

**Comment by kof** [comment]
@AleshaOleg do we put el.style[...] code into try/catch  everywhere?

**Comment by AleshaOleg** [comment]
@kof everywhere, except case described in this issue

**Comment by AleshaOleg** [comment]
Fixed in `2.0.6`.

**Comment by swernerx** [comment]
Thanks a lot!

**Comment by AleshaOleg** [comment]
@swernerx you're welcome :) And thanks for the report
