### ISSUE TITLE
[bug] write-mode is not prefixed properly in Edge

### ISSUE THREAD

**Issue by franklixuefei** [cssinjs/css-vendor#172]
Try this under both Chrome and Edge: https://codesandbox.io/embed/create-react-app-b6iij
Chrome works but edge doesn't.
This doesn't work because the vendor prefixer incorrectly prefixes `-ms-` where no prefix is actually needed there.

**Comment by AleshaOleg** [comment]
@franklixuefei you're right. thanks

**Comment by AleshaOleg** [comment]
https://github.com/cssinjs/css-vendor/pull/175

**Comment by AleshaOleg** [comment]
Released in 2.0.8
