### ISSUE TITLE
Check supported value for dashed transition property

### ISSUE THREAD

**Issue by aChudinov** [cssinjs/css-vendor#47]
When I invoke `supportedValue('transition', 'max-height 100ms linear')`, I have `false-height 100ms linear` as a result.
In general, this happens with any dashed transition property.

**Comment by AleshaOleg** [comment]
https://github.com/cssinjs/css-vendor/pull/49 merged. @aChudinov thanks!

**Comment by aChudinov** [comment]
@AleshaOleg Thank you 😃

**Comment by aChudinov** [comment]
@AleshaOleg Will you take care of propagating these changes to `jss-vendor-prefixer`?

**Comment by AleshaOleg** [comment]
@aChudinov right now preparing build. Have some problems with webpack@4 :)

**Comment by AleshaOleg** [comment]
`css-vendor@1.0.4` released

**Comment by aChudinov** [comment]
Cool, one more thank :)
