### ISSUE TITLE
-apple-trailing-word may not be a reliable way to detect WebKit in future

### ISSUE THREAD

**Issue by smfr** [cssinjs/css-vendor#83]
WebKit is planning to remove support for -apple-trailing-word: https://bugs.webkit.org/show_bug.cgi?id=196525

**Comment by AleshaOleg** [comment]
@smfr thanks for the advice! Are any recommendations, how I can detect Safari without `navigator` like we're doing now, with applying the property to `style`?

**Comment by AleshaOleg** [comment]
https://github.com/cssinjs/css-vendor/pull/86

**Comment by AleshaOleg** [comment]
https://github.com/cssinjs/css-vendor/pull/171

Will release soon
